# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-07 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('D', 'Děti'), ('T', 'Tvoření')], max_length=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
