# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulci', '0002_citation_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='who',
            field=models.CharField(choices=[('V', 'větší'), ('M', 'menší')], max_length=1),
        ),
    ]
